cache:
    - '%LOCALAPPDATA%\pip\Cache'
build: off

environment:
  matrix:

    - TOXENV: 'py35'
      TOXPYTHON: C:\Python35-x64\python.exe
      PYTHON_HOME: C:\Python35-x64
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '32'

    - TOXENV: 'py36'
      TOXPYTHON: C:\Python36-x64\python.exe
      PYTHON_HOME: C:\Python36-x64
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '32'

    - TOXENV: 'py37'
      TOXPYTHON: C:\Python37-x64\python.exe
      PYTHON_HOME: C:\Python37-x64
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '32'

init:
    - ps: echo $env:TOXENV
    - ps: ls C:\Python*

install:
    - '%TOXPYTHON% --version'
    - '%PYTHON_HOME%\Scripts\pip --version'
    - '%TOXPYTHON% -m pip install tox'
    - '%PYTHON_HOME%\Scripts\tox --version'

test_script:
    - '%PYTHON_HOME%\Scripts\tox'

on_failure:
    - ps: dir "env:"
    - ps: get-content .tox\*\log\*
