language: python

python:
  - 3.4
  - 3.5
  - 3.6

env:
  - ALGORITHM=none
  - ALGORITHM=noisy_max_v1a
  - ALGORITHM=noisy_max_v1b
  - ALGORITHM=noisy_max_v2a
  - ALGORITHM=noisy_max_v2b
  - ALGORITHM=SVT
  - ALGORITHM=iSVT1
  - ALGORITHM=iSVT2
  - ALGORITHM=iSVT3

cache: pip

install:
  - pip install tox-travis codecov

script:
  - if [ "$ALGORITHM" = "none" ];
    # test other function except test_core.py which takes a long time
    then travis_wait 120 tox -- -k 'not test_core';
    # split the algorithm tests into different jobs
    else travis_wait 120 tox -- -k 'test_{$ALGORITHM}';
    fi

after_success:
  - codecov

notifications:
  email: false
